# Cereal Analysis

In [2]:
import pandas as pd

In [3]:
# data from https://www.kaggle.com/crawford/80-cereals
df = pd.read_csv('./cereal.csv')
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      77 non-null     object 
 1   mfr       77 non-null     object 
 2   type      77 non-null     object 
 3   calories  77 non-null     int64  
 4   protein   77 non-null     int64  
 5   fat       77 non-null     int64  
 6   sodium    77 non-null     int64  
 7   fiber     77 non-null     float64
 8   carbo     77 non-null     float64
 9   sugars    77 non-null     int64  
 10  potass    77 non-null     int64  
 11  vitamins  77 non-null     int64  
 12  shelf     77 non-null     int64  
 13  weight    77 non-null     float64
 14  cups      77 non-null     float64
 15  rating    77 non-null     float64
dtypes: float64(5), int64(8), object(3)
memory usage: 9.8+ KB


name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C        70        4    1     130   10.0   
1           100% Natural Bran   Q    C       120        3    5      15    2.0   
2                    All-Bran   K    C        70        4    1     260    9.0   
3   All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4              Almond Delight   R    C       110        2    2     200    1.0   
..                        ...  ..  ...       ...      ...  ...     ...    ...   
72                    Triples   G    C       110        2    1     250    0.0   
73                       Trix   G    C       110        1    1     140    0.0   
74                 Wheat Chex   R    C       100        3    1     230    3.0   
75                   Wheaties   G    C       100        3    1     200    3.0   
76        Wheaties Honey Gold   G    C       110        2    1     200    1.0   

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0     5.0       6     280        25      3     1.0  0.33  68.402973  
1     8.0       8     135         0      3     1.0  1.00  33.983679  
2     7.0       5     320        25      3     1.0  0.33  59.425505  
3     8.0       0     330        25      3     1.0  0.50  93.704912  
4    14.0       8      -1        25      3     1.0  0.75  34.384843  
..    ...     ...     ...       ...    ...     ...   ...        ...  
72   21.0       3      60        25      3     1.0  0.75  39.106174  
73   13.0      12      25        25      2     1.0  1.00  27.753301  
74   17.0       3     115        25      1     1.0  0.67  49.787445  
75   17.0       3     110        25      1     1.0  1.00  51.592193  
76   16.0       8      60        25      1     1.0  0.75  36.187559  

[77 rows x 16 columns]

In [4]:
df.head()

name mfr type  calories  protein  fat  sodium  fiber  \
0                  100% Bran   N    C        70        4    1     130   10.0   
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4             Almond Delight   R    C       110        2    2     200    1.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0    5.0       6     280        25      3     1.0  0.33  68.402973  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912  
4   14.0       8      -1        25      3     1.0  0.75  34.384843

In [5]:
df.tail(10)

name mfr type  calories  protein  fat  sodium  fiber  \
67                Special K   K    C       110        6    0     230    1.0   
68  Strawberry Fruit Wheats   N    C        90        2    0      15    3.0   
69        Total Corn Flakes   G    C       110        2    1     200    0.0   
70        Total Raisin Bran   G    C       140        3    1     190    4.0   
71        Total Whole Grain   G    C       100        3    1     200    3.0   
72                  Triples   G    C       110        2    1     250    0.0   
73                     Trix   G    C       110        1    1     140    0.0   
74               Wheat Chex   R    C       100        3    1     230    3.0   
75                 Wheaties   G    C       100        3    1     200    3.0   
76      Wheaties Honey Gold   G    C       110        2    1     200    1.0   

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
67   16.0       3      55        25      1     1.0  1.00  53.131324  
68   15.0       5      90        25      2     1.0  1.00  59.363993  
69   21.0       3      35       100      3     1.0  1.00  38.839746  
70   15.0      14     230       100      3     1.5  1.00  28.592785  
71   16.0       3     110       100      3     1.0  1.00  46.658844  
72   21.0       3      60        25      3     1.0  0.75  39.106174  
73   13.0      12      25        25      2     1.0  1.00  27.753301  
74   17.0       3     115        25      1     1.0  0.67  49.787445  
75   17.0       3     110        25      1     1.0  1.00  51.592193  
76   16.0       8      60        25      1     1.0  0.75  36.187559

In [6]:
# filter the df by columns name and mfr
df[["name", "mfr"]]

name mfr
0                   100% Bran   N
1           100% Natural Bran   Q
2                    All-Bran   K
3   All-Bran with Extra Fiber   K
4              Almond Delight   R
..                        ...  ..
72                    Triples   G
73                       Trix   G
74                 Wheat Chex   R
75                   Wheaties   G
76        Wheaties Honey Gold   G

[77 rows x 2 columns]

In [7]:
df.set_index("name")

mfr type  calories  protein  fat  sodium  fiber  \
name                                                                        
100% Bran                   N    C        70        4    1     130   10.0   
100% Natural Bran           Q    C       120        3    5      15    2.0   
All-Bran                    K    C        70        4    1     260    9.0   
All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
Almond Delight              R    C       110        2    2     200    1.0   
...                        ..  ...       ...      ...  ...     ...    ...   
Triples                     G    C       110        2    1     250    0.0   
Trix                        G    C       110        1    1     140    0.0   
Wheat Chex                  R    C       100        3    1     230    3.0   
Wheaties                    G    C       100        3    1     200    3.0   
Wheaties Honey Gold         G    C       110        2    1     200    1.0   

                           carbo  sugars  potass  vitamins  shelf  weight  \
name                                                                        
100% Bran                    5.0       6     280        25      3     1.0   
100% Natural Bran            8.0       8     135         0      3     1.0   
All-Bran                     7.0       5     320        25      3     1.0   
All-Bran with Extra Fiber    8.0       0     330        25      3     1.0   
Almond Delight              14.0       8      -1        25      3     1.0   
...                          ...     ...     ...       ...    ...     ...   
Triples                     21.0       3      60        25      3     1.0   
Trix                        13.0      12      25        25      2     1.0   
Wheat Chex                  17.0       3     115        25      1     1.0   
Wheaties                    17.0       3     110        25      1     1.0   
Wheaties Honey Gold         16.0       8      60        25      1     1.0   

                           cups     rating  
name                                        
100% Bran                  0.33  68.402973  
100% Natural Bran          1.00  33.983679  
All-Bran                   0.33  59.425505  
All-Bran with Extra Fiber  0.50  93.704912  
Almond Delight             0.75  34.384843  
...                         ...        ...  
Triples                    0.75  39.106174  
Trix                       1.00  27.753301  
Wheat Chex                 0.67  49.787445  
Wheaties                   1.00  51.592193  
Wheaties Honey Gold        0.75  36.187559  

[77 rows x 15 columns]

In [8]:
df[["name","mfr"]].head()

name mfr
0                  100% Bran   N
1          100% Natural Bran   Q
2                   All-Bran   K
3  All-Bran with Extra Fiber   K
4             Almond Delight   R

In [9]:
df.head()

name mfr type  calories  protein  fat  sodium  fiber  \
0                  100% Bran   N    C        70        4    1     130   10.0   
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4             Almond Delight   R    C       110        2    2     200    1.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0    5.0       6     280        25      3     1.0  0.33  68.402973  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912  
4   14.0       8      -1        25      3     1.0  0.75  34.384843

In [10]:
new_df = df[["name","rating","sugars"]].sort_values('rating', ascending=False)
new_df

name     rating  sugars
3   All-Bran with Extra Fiber  93.704912       0
64     Shredded Wheat 'n'Bran  74.472949       0
65  Shredded Wheat spoon size  72.801787       0
0                   100% Bran  68.402973       6
63             Shredded Wheat  68.235885       0
..                        ...        ...     ...
14                Cocoa Puffs  22.736446      13
18              Count Chocula  22.396513      13
35           Honey Graham Ohs  21.871292      11
12      Cinnamon Toast Crunch  19.823573       9
10               Cap'n'Crunch  18.042851      12

[77 rows x 3 columns]

# Find average sodium

In [11]:
avg_sodium = df[["sodium"]].mean()
avg_sodium

sodium    159.675325
dtype: float64

# Find the food with the highest carbohydrate

In [12]:
max_carbohydrate = df['carbo'].max()
max_carbohydrate

23.0

# Show the food name and sugar content of any food with a rating larger than 50

In [13]:
highly_rated_food =  df[df['rating'] > 50][['name', 'sugars']]
highly_rated_food.set_index('name')

sugars
name                             
100% Bran                       6
All-Bran                        5
All-Bran with Extra Fiber       0
Bran Flakes                     5
Cheerios                        1
Cream of Wheat (Quick)          0
Frosted Mini-Wheats             7
Grape Nuts Flakes               5
Grape-Nuts                      3
Maypo                           3
Nutri-grain Wheat               2
Puffed Rice                     0
Puffed Wheat                    0
Quaker Oatmeal                 -1
Raisin Squares                  6
Shredded Wheat                  0
Shredded Wheat 'n'Bran          0
Shredded Wheat spoon size       0
Special K                       3
Strawberry Fruit Wheats         5
Wheaties                        3

In [14]:
mcc =  df['carbo'].mode()
mcc

0    13.0
1    15.0
dtype: float64

In [15]:
import numpy as np
df[df['carbo'] == np.mean(mcc)][['name', 'carbo']].set_index('name')

carbo
name                      
Almond Delight        14.0
Frosted Flakes        14.0
Frosted Mini-Wheats   14.0
Fruitful Bran         14.0
Honey-comb            14.0
Quaker Oat Squares    14.0
Raisin Bran           14.0

# Standard Deviation
## Average distance of a value from the mean

In [16]:
df['potass'].std()

71.28681250926212

## What is the median value for protein and sugars across / for/  per each manufacturer?

In [18]:
df[['mfr','sugars','protein']].groupby('mfr').median()

sugars  protein
mfr                 
A       3.0      4.0
G       8.5      2.0
K       7.0      3.0
N       0.0      3.0
P      10.0      3.0
Q       6.0      2.5
R       5.5      2.0

In [24]:
def manufacturer_names(mfr):
    map = {
        "A": "Alfalfa",
        "G": 'General Mills',
        "K": 'Kellogs',
        "N": 'Nabisco',
        "P": 'Post',
        "Q": 'Quaker',
        "R": 'Ralcorp',
    }
    return map.get(mfr)

df['Manufacturer'] = df['mfr'].apply(manufacturer_names)
df

name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C        70        4    1     130   10.0   
1           100% Natural Bran   Q    C       120        3    5      15    2.0   
2                    All-Bran   K    C        70        4    1     260    9.0   
3   All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4              Almond Delight   R    C       110        2    2     200    1.0   
..                        ...  ..  ...       ...      ...  ...     ...    ...   
72                    Triples   G    C       110        2    1     250    0.0   
73                       Trix   G    C       110        1    1     140    0.0   
74                 Wheat Chex   R    C       100        3    1     230    3.0   
75                   Wheaties   G    C       100        3    1     200    3.0   
76        Wheaties Honey Gold   G    C       110        2    1     200    1.0   

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating  \
0     5.0       6     280        25      3     1.0  0.33  68.402973   
1     8.0       8     135         0      3     1.0  1.00  33.983679   
2     7.0       5     320        25      3     1.0  0.33  59.425505   
3     8.0       0     330        25      3     1.0  0.50  93.704912   
4    14.0       8      -1        25      3     1.0  0.75  34.384843   
..    ...     ...     ...       ...    ...     ...   ...        ...   
72   21.0       3      60        25      3     1.0  0.75  39.106174   
73   13.0      12      25        25      2     1.0  1.00  27.753301   
74   17.0       3     115        25      1     1.0  0.67  49.787445   
75   17.0       3     110        25      1     1.0  1.00  51.592193   
76   16.0       8      60        25      1     1.0  0.75  36.187559   

     Manufacturer  
0         Nabisco  
1          Quaker  
2         Kellogs  
3         Kellogs  
4         Ralcorp  
..            ...  
72  General Mills  
73  General Mills  
74        Ralcorp  
75  General Mills  
76  General Mills  

[77 rows x 17 columns]

In [26]:
items = ['a','b']
for index, item in enumerate(items):
    print(index)
    print(item)


0
a
1
b


## Things you need to figure out for the lab

- slicing
- iloc
- data cleaning
    - dropna    
- handling missing data
    -fillna
- date_time.now
- isnull
- indexing
- sum
- How to dig into data to find patterns or make sense of a data set


In [27]:
nums = [1,2,3]
nums + 4

TypeError: can only concatenate list (not "int") to list

In [29]:
# Broadcasting
a = np.array([1,2,3])
print(a)
b = 4
print(b)
c = a + b
print(c)

[1 2 3]
4
[5 6 7]


In [30]:
# Broadcasting
a = np.array([[1,2,3],[1,2,3]])
print(a)
b = 4
print(b)
c = a + b
print(c)

[[1 2 3]
 [1 2 3]]
4
[[5 6 7]
 [5 6 7]]


In [31]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b = np.array([7, 8, 9])
print(b)
c = a + b
print(c)

[[1 2 3]
 [4 5 6]]
[7 8 9]
[[ 8 10 12]
 [11 13 15]]


In [32]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b = np.array([7, 8, 9, 10])
print(b)
c = a + b
print(c)

[[1 2 3]
 [4 5 6]]
[ 7  8  9 10]


ValueError: operands could not be broadcast together with shapes (2,3) (4,) 